[project]
name = "ussplitter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
license = "LGPL-3.0-or-later"
requires-python = "~=3.11"
dependencies = [
    "demucs>=4.0.1",
    "flask>=3.1.0",
    "gunicorn>=23.0.0",
    "numpy~=1.24.1",
    "platformdirs>=4.3.6",
]

[tool.uv]
default-groups = ["dev"]

[tool.uv.sources]
torch = [
  { index = "pytorch-cu121", marker = "platform_system != 'Darwin'"},
]
torchvision = [
  { index = "pytorch-cu121", marker = "platform_system != 'Darwin'"},
]
torchaudio = [
  { index = "pytorch-cu121", marker = "platform_system != 'Darwin'"},
]
demucs = { git = "https://github.com/adefossez/demucs", rev = "b9ab48cad45976ba42b2ff17b229c071f0df9390" }
usdb-syncer = { git = "https://github.com/randompersona1/usdb_syncer", branch = "python3.11" }

[[tool.uv.index]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
explicit = true

[dependency-groups]
dev = [
    "usdb-syncer",
    "isort>=5.13.2",
    "ruff>=0.9.3",
]
torch = [
    "torch>=2.1.2",
    "torchaudio<2.2.0",
]
