name: Ruff
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check project with ruff linter
        uses: astral-sh/ruff-action@v3
        with:
          args: "check"
      - name: Check project with ruff formatter
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
      - name: Run mypy
        run: uv run mypy src