name: Ruff
on: [ push, pull_request ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check project with ruff linter
        uses: astral-sh/ruff-action@v3
        with:
          args: "check"
      - name: Check project with ruff formatter
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
      - name: Install system dependencies for dbus-python
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libdbus-1-dev libglib2.0-dev
          pkg-config --cflags --libs dbus-1
      - name: Generate pyside files
        run: uv run ./scripts/pyside_uic.py
      - name: Run mypy
        run: uv run mypy src